"""Add ranking and section columns

Revision ID: 1b7081a1ef1b
Revises: eba5c0cad202
Create Date: 2025-09-03 14:48:12.239242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b7081a1ef1b'
down_revision = 'eba5c0cad202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.add_column(sa.Column('section', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.drop_column('section')

    # ### end Alembic commands ###
