"""Add post_title field

Revision ID: 81cdbdc3aaba
Revises: 1b7081a1ef1b
Create Date: 2025-09-03 23:41:18.093099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81cdbdc3aaba'
down_revision = '1b7081a1ef1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.add_column(sa.Column('post_title', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.drop_column('post_title')

    # ### end Alembic commands ###
