"""Add ranking column to Keyword model

Revision ID: eba5c0cad202
Revises: b91c45756940
Create Date: 2025-09-03 14:32:08.180116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba5c0cad202'
down_revision = 'b91c45756940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranking', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keyword', schema=None) as batch_op:
        batch_op.drop_column('ranking')

    # ### end Alembic commands ###
